[fix] put docs on separate line from block comment marker (#138)
<!-- PR title should start with '[fix]', '[improvement]' or '[break]' if this PR would cause a patch, minor or major SemVer bump. Omit the prefix if this PR doesn't warrant a standalone release. -->

## Before this PR
<!-- Describe the problem you encountered with the current state of the world (or link to an issue) and why it's important to fix now. -->

Conjure documentation strings that happened to begin or end with a quote symbol (`"`) would break block comment escaping and cause the interpreter to fail.

```yml
 ...
 docs: These are the docs "this part is quoted"
 ...
```

renders in python as 

```python
	"""These are the docs "this part is quoted""""
```

and the interpreter says:

```python
SyntaxError: EOL while scanning string literal
```

## After this PR
<!-- Describe at a high-level why this approach is better. -->

By putting the docstring on a separate line from the block comment markers we avoid this conflict.


```python
	"""
	These are the docs "this part is quoted"
	"""
```

<!-- Reference any existing GitHub issues, e.g. 'fixes #000' or 'relevant to #000' -->